### ISSUE TITLE
Any chances to have TypeScript one?

### ISSUE THREAD

**Issue by devhindo** [KiddoV/wails-pure-js-template#1]
with some modifications like adding `tsconfig.json` that outputs the js to the same directory that currently holds the js files would create a cool typescript starter template

**Comment by KiddoV** [comment]
The goal of this Wails template is to provide a JavaScript file without any dependencies on TypeScript or modules in the ``node_modules`` directory. If you prefer a TypeScript template, I recommend using the official [Wails vanilla-ts](https://wails.io/docs/gettingstarted/firstproject) template, which you can create using the following CLI command:
```cli
wails init -n <myproject> -t vanilla-ts
```
Thanks!
