### ISSUE TITLE
in `Live Development` section no `package.json` to allow running `npm run dev`

### ISSUE THREAD

**Issue by devhindo** [KiddoV/wails-pure-js-template#2]

**Comment by KiddoV** [comment]
Related to issue #1,
Again, this template aims to avoid using the extensive "node_modules" folder for dependencies. If you prefer to use ``package.json``, I would recommend using Wails's official vanilla templates, which can be found at:
https://wails.io/docs/gettingstarted/firstproject
Thank you!

**Comment by devhindo** [comment]
I guess then removing [this](https://github.com/KiddoV/wails-pure-js-template#live-development) section would be reasonable

**Comment by KiddoV** [comment]
Thanks for pointing that out. I definitely forgot about that part as the README was auto generated. I will make changes in the README!

**Comment by KiddoV** [comment]
Fixed. Thanks again @devhindo !
